server:
  port: 28114
  ssl:
    key-store: classpath:config/server.keystore
    key-store-password: mrjiang@123.
spring:
  application:
    name: service-secws
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:28110/eureka/
  instance:
    preferIpAddress: true

